export const WORD_CLUES: [string, string][] = [
  ["ACE", "Top card"], ["ACT", "Stage performance"], ["ADD", "Sum up"], ["AGE", "How old"],
  ["AID", "Help"], ["AIM", "Target"], ["AIR", "Breathe it"], ["ALE", "Pub drink"],
  ["APE", "Primate"], ["ARC", "Curved line"], ["ARK", "Noah's vessel"], ["ARM", "Body limb"],
  ["ART", "Creative work"], ["ATE", "Past of eat"], ["AWE", "Wonder"],
  ["BAD", "Not good"], ["BAG", "Carry-all"], ["BAN", "Prohibit"], ["BAR", "Tavern"],
  ["BAT", "Flying mammal"], ["BED", "Sleep furniture"], ["BIG", "Large"], ["BIT", "Small piece"],
  ["BOW", "Ribbon knot"], ["BOX", "Container"], ["BOY", "Young male"], ["BUD", "Flower start"],
  ["BUG", "Insect"], ["BUS", "Transit vehicle"], ["BUT", "However"], ["BUY", "Purchase"],
  ["CAB", "Taxi"], ["CAN", "Metal container"], ["CAP", "Head cover"], ["CAR", "Automobile"],
  ["CAT", "Feline pet"], ["CUP", "Drinking vessel"], ["CUT", "Slice"],
  ["DAD", "Father"], ["DAM", "River barrier"], ["DAY", "24 hours"], ["DIG", "Excavate"],
  ["DIM", "Faintly lit"], ["DIP", "Submerge briefly"], ["DOG", "Canine companion"],
  ["DOT", "Small spot"], ["DRY", "Not wet"], ["DUG", "Past of dig"], ["DYE", "Color fabric"],
  ["EAR", "Hearing organ"], ["EAT", "Consume food"], ["EEL", "Snake fish"], ["EGG", "Oval food"],
  ["ELF", "Small fairy"], ["ELM", "Shade tree"], ["END", "Finish"], ["ERA", "Time period"],
  ["EVE", "Night before"], ["EWE", "Female sheep"], ["EYE", "Sight organ"],
  ["FAN", "Cool breeze maker"], ["FAR", "Distant"], ["FAT", "Not thin"], ["FIG", "Sweet fruit"],
  ["FIN", "Fish limb"], ["FIT", "In good shape"], ["FIX", "Repair"], ["FLY", "Soar"],
  ["FOG", "Thick mist"], ["FOR", "In favor of"], ["FOX", "Cunning animal"], ["FUN", "Enjoyment"],
  ["FUR", "Animal coat"], ["GAP", "Opening"], ["GAS", "Fuel"], ["GEM", "Precious stone"],
  ["GIN", "Clear spirit"], ["GNU", "Wildebeest"], ["GOD", "Deity"], ["GUM", "Chewing treat"],
  ["GUN", "Firearm"], ["GUT", "Intestine"], ["GUY", "Fellow"],
  ["HAD", "Possessed"], ["HAM", "Cured pork"], ["HAS", "Possesses"], ["HAT", "Head wear"],
  ["HAY", "Dried grass"], ["HEN", "Female chicken"], ["HER", "Belonging to she"],
  ["HID", "Concealed"], ["HIM", "That man"], ["HIT", "Strike"], ["HOG", "Pig"],
  ["HOP", "Small jump"], ["HOT", "High temperature"], ["HOW", "In what way"], ["HUG", "Embrace"],
  ["HUM", "Sing closed-mouthed"],
  ["ICE", "Frozen water"], ["ILL", "Sick"], ["IMP", "Little devil"], ["INK", "Pen fluid"],
  ["INN", "Small hotel"], ["ION", "Charged atom"], ["IRE", "Anger"], ["IVY", "Climbing plant"],
  ["JAB", "Quick punch"], ["JAM", "Fruit spread"], ["JAR", "Glass container"], ["JAW", "Mouth bone"],
  ["JET", "Fast plane"], ["JOB", "Employment"], ["JOG", "Light run"], ["JOY", "Happiness"],
  ["JUG", "Pouring vessel"],
  ["KEG", "Beer barrel"], ["KEN", "Knowledge"], ["KEY", "Lock opener"], ["KID", "Child"],
  ["KIN", "Relatives"], ["KIT", "Set of tools"],
  ["LAP", "Circuit"], ["LAW", "Legal rule"], ["LAY", "Put down"], ["LED", "Guided"],
  ["LEG", "Walking limb"], ["LET", "Allow"], ["LID", "Cover"], ["LIE", "Untruth"],
  ["LIP", "Mouth edge"], ["LOG", "Wood piece"], ["LOT", "Large amount"], ["LOW", "Not high"],
  ["ABLE", "Capable"], ["ACID", "Sour chemical"], ["AGED", "Old"], ["ALSO", "In addition"],
  ["AREA", "Region"], ["ARMY", "Military force"], ["AUNT", "Parent's sister"],
  ["BAKE", "Cook in oven"], ["BALD", "No hair"], ["BALL", "Round toy"], ["BAND", "Music group"],
  ["BANK", "Money holder"], ["BARE", "Uncovered"], ["BARN", "Farm building"],
  ["BASE", "Foundation"], ["BATH", "Wash in tub"], ["BEAM", "Light ray"], ["BEAN", "Pod vegetable"],
  ["BEAR", "Large mammal"], ["BEAT", "Rhythm"], ["BELL", "Ringing device"], ["BELT", "Waist strap"],
  ["BEND", "Curve"], ["BIKE", "Two-wheeler"], ["BIRD", "Feathered flyer"], ["BITE", "Chomp"],
  ["BLOW", "Wind gust"], ["BLUE", "Sky color"], ["BOAT", "Water vessel"], ["BODY", "Physical form"],
  ["BOLD", "Courageous"], ["BOLT", "Door fastener"], ["BOMB", "Explosive"], ["BOND", "Connection"],
  ["BONE", "Skeleton part"], ["BOOK", "Reading material"], ["BOOT", "Foot covering"],
  ["BORE", "Drill or dull person"], ["BORN", "Brought to life"], ["BOSS", "Manager"],
  ["BOWL", "Deep dish"], ["BULK", "Large quantity"], ["BURN", "Fire damage"],
  ["CAGE", "Animal enclosure"], ["CAKE", "Birthday dessert"], ["CALM", "Peaceful"],
  ["CAME", "Arrived"], ["CAMP", "Outdoor stay"], ["CAPE", "Superhero garment"],
  ["CARD", "Playing piece"], ["CARE", "Concern"], ["CART", "Wheeled carrier"],
  ["CASE", "Container or situation"], ["CASH", "Money"], ["CAST", "Throw"],
  ["CAVE", "Natural hollow"], ["CHEF", "Master cook"], ["CHIP", "Snack or fragment"],
  ["CITY", "Urban area"], ["CLAM", "Shellfish"], ["CLAY", "Pottery material"],
  ["CLIP", "Fasten together"], ["CLUB", "Social group"], ["CLUE", "Hint"],
  ["COAL", "Black fuel"], ["COAT", "Outer garment"], ["CODE", "Secret language"],
  ["COIN", "Metal money"], ["COLD", "Low temperature"], ["COMB", "Hair tool"],
  ["CONE", "Ice cream holder"], ["COOK", "Prepare food"], ["COOL", "Slightly cold"],
  ["COPY", "Duplicate"], ["CORD", "Thin rope"], ["CORE", "Center"], ["CORK", "Bottle stopper"],
  ["CORN", "Cereal grain"], ["COST", "Price"], ["COZY", "Warm and snug"],
  ["CREW", "Ship workers"], ["CROP", "Farm harvest"], ["CROW", "Black bird"],
  ["CUBE", "3D square"], ["CURE", "Remedy"],
  ["DALE", "Valley"], ["DAME", "Lady"], ["DAMP", "Slightly wet"], ["DARE", "Challenge"],
  ["DARK", "Without light"], ["DART", "Pointed missile"], ["DATA", "Information"],
  ["DAWN", "Daybreak"], ["DEAL", "Agreement"], ["DEAR", "Beloved"], ["DECK", "Ship floor"],
  ["DEED", "Action"], ["DEEM", "Consider"], ["DEEP", "Far down"], ["DEER", "Forest animal"],
  ["DENY", "Refuse"], ["DESK", "Work table"], ["DIAL", "Phone face"],
  ["DICE", "Game cubes"], ["DIET", "Food plan"], ["DIME", "Ten cents"],
  ["DINE", "Eat formally"], ["DIRT", "Soil"], ["DISH", "Plate"], ["DISK", "Round object"],
  ["DOCK", "Harbor pier"], ["DOME", "Rounded roof"], ["DONE", "Finished"],
  ["DOOR", "Room entrance"], ["DOSE", "Medicine amount"], ["DOVE", "Peace bird"],
  ["DOWN", "Below"], ["DRAW", "Sketch"], ["DREW", "Past of draw"],
  ["DROP", "Fall"], ["DRUM", "Percussion"], ["DUAL", "Double"], ["DUCK", "Waterfowl"],
  ["DUEL", "One-on-one fight"], ["DUKE", "Noble title"], ["DULL", "Not sharp"],
  ["DUMP", "Discard"], ["DUNE", "Sand hill"], ["DUSK", "Twilight"], ["DUST", "Fine particles"],
  ["DUTY", "Obligation"],
  ["EAGLE", "Majestic bird"], ["EARTH", "Our planet"], ["EIGHT", "Number after seven"],
  ["FLAME", "Fire tongue"], ["FLASH", "Brief light"], ["FLOAT", "Stay on surface"],
  ["FLOOD", "Water overflow"], ["FLOOR", "Room bottom"], ["FLOUR", "Baking powder"],
  ["FLUTE", "Wind instrument"],
  ["GHOST", "Spirit"], ["GIANT", "Very large person"], ["GLOBE", "World sphere"],
  ["GRACE", "Elegance"], ["GRAIN", "Cereal seed"], ["GRAPE", "Wine fruit"],
  ["GRAPH", "Data chart"], ["GRASS", "Lawn plant"], ["GRAVE", "Burial site"],
  ["GREEN", "Grass color"], ["GRIND", "Crush fine"], ["GUARD", "Protector"],
  ["GUESS", "Estimate"], ["GUIDE", "Leader"],
  ["HABIT", "Regular practice"], ["HEART", "Vital organ"], ["HEAVY", "Weighs a lot"],
  ["HEDGE", "Garden border"], ["HONEY", "Bee product"], ["HORSE", "Riding animal"],
  ["HOTEL", "Guest lodging"], ["HOUSE", "Dwelling"], ["HUMAN", "Person"],
  ["IMAGE", "Picture"], ["JUICE", "Fruit drink"],
  ["KNIFE", "Cutting tool"], ["LEMON", "Sour citrus"], ["LIGHT", "Illumination"],
  ["MAPLE", "Syrup tree"], ["MEDAL", "Award disc"], ["MOUSE", "Small rodent"],
  ["MUSIC", "Melodic art"], ["NIGHT", "After sunset"], ["NOBLE", "Of high rank"],
  ["OCEAN", "Vast sea"], ["OLIVE", "Green fruit"], ["OPERA", "Sung drama"],
  ["ORBIT", "Circular path"], ["ORGAN", "Body part or instrument"],
  ["PAINT", "Color coating"], ["PAPER", "Writing sheet"], ["PEARL", "Oyster gem"],
  ["PIANO", "Keyboard instrument"], ["PILOT", "Aircraft driver"], ["PLANT", "Green organism"],
  ["PLATE", "Eating dish"], ["PLAZA", "Open square"], ["PLUMB", "Straight down"],
  ["POLAR", "Arctic or Antarctic"], ["POUND", "Weight unit"], ["POWER", "Strength"],
  ["PRIDE", "Self-respect"], ["PRIME", "First-rate"], ["PRINT", "Put on paper"],
  ["PRIZE", "Award"], ["PROBE", "Investigate"], ["PRUNE", "Dried plum"],
  ["QUEEN", "Female monarch"], ["QUIET", "Silent"], ["QUILT", "Bed cover"],
  ["QUOTE", "Repeat words"],
  ["RADIO", "Broadcast receiver"], ["RAISE", "Lift up"], ["RANCH", "Cattle farm"],
  ["RAPID", "Very fast"], ["RAVEN", "Black bird"], ["REACH", "Extend to"],
  ["REIGN", "Rule"], ["RIDER", "Horseback person"], ["RIDGE", "Mountain crest"],
  ["RIGHT", "Correct"], ["RIVER", "Flowing water"], ["ROAST", "Cook with heat"],
  ["ROBOT", "Mechanical worker"], ["ROCKY", "Full of stones"], ["ROUND", "Circular"],
  ["ROYAL", "Of the king"], ["RULER", "Measuring stick"],
  ["SAINT", "Holy person"], ["SALAD", "Mixed greens"], ["SCALE", "Measuring device"],
  ["SCARE", "Frighten"], ["SCENE", "View or setting"], ["SCORE", "Points earned"],
  ["SHADE", "Partial shadow"], ["SHAKE", "Tremble"], ["SHAME", "Disgrace"],
  ["SHAPE", "Form or figure"], ["SHARE", "Divide equally"], ["SHARK", "Ocean predator"],
  ["SHARP", "Keen edge"], ["SHAVE", "Remove hair"], ["SHEEP", "Woolly animal"],
  ["SHELL", "Hard outer cover"], ["SHIFT", "Move or change"], ["SHINE", "Give off light"],
  ["SHIRT", "Upper garment"], ["SHOCK", "Sudden surprise"], ["SHORE", "Beach"],
  ["SIGHT", "Vision"], ["SILLY", "Foolish"], ["SINCE", "From then"],
  ["SKATE", "Glide on ice"], ["SKILL", "Ability"], ["SKULL", "Head bone"],
  ["SLEEP", "Rest at night"], ["SLICE", "Thin piece"], ["SLIDE", "Glide down"],
  ["SLOPE", "Incline"], ["SMALL", "Little"], ["SMART", "Intelligent"],
  ["SMELL", "Nose sense"], ["SMILE", "Happy expression"], ["SMOKE", "Fire output"],
  ["SNAIL", "Slow creature"], ["SNAKE", "Legless reptile"], ["SOLAR", "Of the sun"],
  ["SOLID", "Not liquid"], ["SOLVE", "Find answer"], ["SOUND", "Noise"],
  ["SOUTH", "Compass direction"], ["SPACE", "Outer void"], ["SPARE", "Extra"],
  ["SPEAK", "Talk"], ["SPEED", "Rate of motion"], ["SPELL", "Magic words"],
  ["SPEND", "Use money"], ["SPICE", "Food seasoning"], ["SPINE", "Backbone"],
  ["SPLIT", "Divide"], ["SPOON", "Eating utensil"], ["SPORT", "Athletic game"],
  ["SPRAY", "Fine mist"], ["SQUAD", "Small team"], ["STAGE", "Theater platform"],
  ["STAIN", "Spot or mark"], ["STAIR", "Step"], ["STAKE", "Pointed post"],
  ["STALE", "Not fresh"], ["STALL", "Delay"], ["STAMP", "Postage mark"],
  ["STAND", "Be upright"], ["STARE", "Look fixedly"], ["START", "Begin"],
  ["STATE", "Condition"], ["STAYS", "Remains"], ["STEAK", "Beef cut"],
  ["STEAL", "Take wrongly"], ["STEAM", "Water vapor"], ["STEEL", "Strong metal"],
  ["STEEP", "Sharply inclined"], ["STEER", "Guide a vehicle"], ["STERN", "Ship rear"],
  ["STICK", "Thin branch"], ["STILL", "Motionless"], ["STOCK", "Supply"],
  ["STONE", "Rock"], ["STOOD", "Past of stand"], ["STORE", "Shop"],
  ["STORM", "Violent weather"], ["STORY", "Tale"], ["STOVE", "Cooking appliance"],
  ["STRAW", "Drinking tube"], ["STRIP", "Narrow piece"], ["STUCK", "Unable to move"],
  ["STUDY", "Learn"], ["STUFF", "Material"], ["STUMP", "Tree remainder"],
  ["STYLE", "Fashion"], ["SUGAR", "Sweet crystal"], ["SUITE", "Hotel rooms"],
  ["SURGE", "Sudden increase"], ["SWAMP", "Wetland"], ["SWEAR", "Vow"],
  ["SWEEP", "Clean with broom"], ["SWEET", "Sugary taste"], ["SWIFT", "Very fast"],
  ["SWING", "Back and forth"], ["SWORD", "Bladed weapon"],
  ["TABLE", "Flat furniture"], ["TASTE", "Flavor sense"], ["TEACH", "Instruct"],
  ["THANK", "Express gratitude"], ["THICK", "Not thin"], ["THING", "Object"],
  ["THINK", "Use the mind"], ["THORN", "Plant spike"], ["THREE", "Number after two"],
  ["THROW", "Toss"], ["THUMB", "Short finger"], ["TIGER", "Striped cat"],
  ["TOAST", "Browned bread"], ["TODAY", "This day"], ["TOKEN", "Symbol or sign"],
  ["TOTAL", "Complete sum"], ["TOUCH", "Feel with hand"], ["TOWER", "Tall structure"],
  ["TOXIC", "Poisonous"], ["TRACE", "Follow path"], ["TRACK", "Path or trail"],
  ["TRADE", "Exchange"], ["TRAIL", "Hiking path"], ["TRAIN", "Rail vehicle"],
  ["TRAIT", "Characteristic"], ["TRASH", "Garbage"], ["TREAT", "Special reward"],
  ["TREND", "Current fashion"], ["TRIAL", "Court case"], ["TRIBE", "Social group"],
  ["TRICK", "Clever act"], ["TRIED", "Attempted"], ["TROUT", "River fish"],
  ["TRUCK", "Large vehicle"], ["TRULY", "Honestly"], ["TRUNK", "Tree stem"],
  ["TRUST", "Believe in"], ["TRUTH", "Fact"], ["TULIP", "Spring flower"],
  ["TUMOR", "Growth"], ["TUNER", "Radio adjuster"], ["TWICE", "Two times"],
  ["TWIST", "Turn or wind"],
  ["UNCLE", "Parent's brother"], ["UNDER", "Below"], ["UNION", "Joined together"],
  ["UNITE", "Bring together"], ["UNITY", "Oneness"], ["UNTIL", "Up to"],
  ["UPPER", "Higher"], ["URBAN", "City-related"], ["USUAL", "Normal"],
  ["VALVE", "Flow controller"], ["VAULT", "Secure room"], ["VERSE", "Poem line"],
  ["VIDEO", "Moving images"], ["VIGOR", "Energy"], ["VIOLA", "String instrument"],
  ["VIRAL", "Spreading fast"], ["VISIT", "Go to see"], ["VITAL", "Essential"],
  ["VIVID", "Bright and clear"], ["VOCAL", "Using voice"], ["VOICE", "Speaking sound"],
  ["VOTER", "Election participant"],
  ["WAGES", "Pay"], ["WASTE", "Squander"], ["WATCH", "Timepiece"],
  ["WATER", "H2O"], ["WEAVE", "Interlace threads"], ["WEDGE", "Tapered block"],
  ["WEIGH", "Measure mass"], ["WHALE", "Ocean giant"], ["WHEAT", "Bread grain"],
  ["WHEEL", "Circular frame"], ["WHERE", "At what place"], ["WHILE", "During"],
  ["WHITE", "Snow color"], ["WHOLE", "Entire"], ["WIDEN", "Make broader"],
  ["WIDTH", "Breadth"], ["WITCH", "Magic woman"], ["WOMAN", "Adult female"],
  ["WORLD", "Earth"], ["WORRY", "Anxiety"], ["WORSE", "Less good"],
  ["WORTH", "Value"], ["WOUND", "Injury"], ["WRIST", "Hand joint"],
  ["WRITE", "Put words down"],
  ["YACHT", "Luxury boat"], ["YIELD", "Produce or give way"], ["YOUNG", "Not old"],
  ["YOUTH", "Young age"], ["ZEBRA", "Striped animal"], ["ZONE", "Area"],
];

export const WORDS: string[] = WORD_CLUES.map(([w]) => w);

export const QUOTES: string[] = [
  "THE ONLY WAY TO DO GREAT WORK IS TO LOVE WHAT YOU DO",
  "IN THE MIDDLE OF DIFFICULTY LIES OPPORTUNITY",
  "LIFE IS WHAT HAPPENS WHEN YOU ARE BUSY MAKING OTHER PLANS",
  "THE FUTURE BELONGS TO THOSE WHO BELIEVE IN THE BEAUTY OF THEIR DREAMS",
  "IT IS DURING OUR DARKEST MOMENTS THAT WE MUST FOCUS TO SEE THE LIGHT",
  "THE PURPOSE OF OUR LIVES IS TO BE HAPPY",
  "LIFE IS REALLY SIMPLE BUT WE INSIST ON MAKING IT COMPLICATED",
  "THE BEST TIME TO PLANT A TREE WAS TWENTY YEARS AGO THE SECOND BEST TIME IS NOW",
  "AN UNEXAMINED LIFE IS NOT WORTH LIVING",
  "YOUR TIME IS LIMITED SO DO NOT WASTE IT LIVING SOMEONE ELSES LIFE",
  "IF YOU TELL THE TRUTH YOU DO NOT HAVE TO REMEMBER ANYTHING",
  "YOU MISS ONE HUNDRED PERCENT OF THE SHOTS YOU DO NOT TAKE",
  "THE GREATEST GLORY IN LIVING LIES NOT IN NEVER FALLING BUT IN RISING EVERY TIME WE FALL",
  "THE WAY TO GET STARTED IS TO QUIT TALKING AND BEGIN DOING",
  "IF LIFE WERE PREDICTABLE IT WOULD CEASE TO BE LIFE AND BE WITHOUT FLAVOR",
  "SPREAD LOVE EVERYWHERE YOU GO LET NO ONE EVER COME TO YOU WITHOUT LEAVING HAPPIER",
  "WHEN YOU REACH THE END OF YOUR ROPE TIE A KNOT IN IT AND HANG ON",
  "ALWAYS REMEMBER THAT YOU ARE ABSOLUTELY UNIQUE JUST LIKE EVERYONE ELSE",
  "THE ONLY IMPOSSIBLE JOURNEY IS THE ONE YOU NEVER BEGIN",
  "IN THIS LIFE WE CANNOT DO GREAT THINGS WE CAN ONLY DO SMALL THINGS WITH GREAT LOVE",
  "MANY OF LIFES FAILURES ARE PEOPLE WHO DID NOT REALIZE HOW CLOSE THEY WERE WHEN THEY GAVE UP",
  "WHOEVER IS HAPPY WILL MAKE OTHERS HAPPY TOO",
  "DO NOT LET YESTERDAY TAKE UP TOO MUCH OF TODAY",
  "IT IS NEVER TOO LATE TO BE WHAT YOU MIGHT HAVE BEEN",
  "EVERYTHING YOU CAN IMAGINE IS REAL",
  "NOTHING IS IMPOSSIBLE THE WORD ITSELF SAYS I AM POSSIBLE",
  "BELIEVE YOU CAN AND YOU ARE HALFWAY THERE",
  "ACT AS IF WHAT YOU DO MAKES A DIFFERENCE BECAUSE IT DOES",
  "SUCCESS IS NOT FINAL FAILURE IS NOT FATAL IT IS THE COURAGE TO CONTINUE THAT COUNTS",
  "THE MIND IS EVERYTHING WHAT YOU THINK YOU BECOME",
];
