// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/get-my-profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
function sb(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my Puzzlecraft profile",
  description: "Return the signed-in user's Puzzlecraft profile: display name, rating, skill tier, total solves, friend code, and Puzzlecraft+ status.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await sb(ctx).from("user_profiles").select(
      "display_name, rating, rating_tier, solves_count, friend_code, is_premium, subscribed"
    ).eq("id", ctx.getUserId()).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: "Profile not found" }], isError: true };
    }
    const summary = `Player: ${data.display_name ?? "(unnamed)"}
Rating: ${data.rating ?? 0} (${data.rating_tier ?? "Unrated"})
Solves: ${data.solves_count ?? 0}
Friend code: ${data.friend_code ?? "\u2014"}
Puzzlecraft+: ${data.subscribed ? "active" : "inactive"}`;
    return {
      content: [{ type: "text", text: summary }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/get-my-stats.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
function sb2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_my_stats_default = defineTool2({
  name: "get_my_stats",
  title: "Get my Puzzlecraft stats",
  description: "Return the signed-in user's per-puzzle-type rating breakdown from the type leaderboards (crossword, sudoku, nonogram, etc.).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await sb2(ctx).from("type_leaderboard_entries").select("puzzle_type, rating, skill_tier, solve_count").eq("user_id", ctx.getUserId()).order("rating", { ascending: false });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const rows = data ?? [];
    if (rows.length === 0) {
      return {
        content: [{ type: "text", text: "No per-type ratings yet \u2014 solve a puzzle to get started." }],
        structuredContent: { types: [] }
      };
    }
    const lines = rows.map(
      (r) => `${r.puzzle_type}: ${r.rating} (${r.skill_tier}, ${r.solve_count} solves)`
    );
    return {
      content: [{ type: "text", text: lines.join("\n") }],
      structuredContent: { types: rows }
    };
  }
});

// src/lib/mcp/tools/get-leaderboard.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.99.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
function sb3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_leaderboard_default = defineTool3({
  name: "get_leaderboard",
  title: "Get Puzzlecraft leaderboard",
  description: "Return the top Puzzlecraft players by overall rating. Use `limit` (1-50, default 10) to control how many rows come back.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("How many top players to return. Default 10.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const n = limit ?? 10;
    const { data, error } = await sb3(ctx).from("leaderboard_entries").select("display_name, rating, skill_tier, solve_count").order("rating", { ascending: false }).limit(n);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const rows = data ?? [];
    const lines = rows.map(
      (r, i) => `${i + 1}. ${r.display_name} \u2014 ${r.rating} (${r.skill_tier}, ${r.solve_count} solves)`
    );
    return {
      content: [
        { type: "text", text: lines.length ? lines.join("\n") : "Leaderboard is empty." }
      ],
      structuredContent: { entries: rows }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "nkfxdupsbxgbclsgseez";
var mcp_default = defineMcp({
  name: "puzzlecraft-mcp",
  title: "Puzzlecraft",
  version: "0.1.0",
  instructions: "Tools for the Puzzlecraft puzzle app. Use `get_my_profile` for the signed-in player's overall rating and tier, `get_my_stats` for their rating per puzzle type, and `get_leaderboard` for the global top players.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_my_profile_default, get_my_stats_default, get_leaderboard_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
